### ISSUE TITLE
wrong formatting 

### ISSUE THREAD

**Issue by aldinezi** [OriStranac/BookFinder#23]
indentation is messed up

https://github.com/OriStranac/BookFinder/blob/20d14679024cf6237d89479d1e1a81f0fd1e633d/src/store/mutations.js#L1-L21

**Comment by aldinezi** [comment]
also wrong indentation

https://github.com/OriStranac/BookFinder/blob/20d14679024cf6237d89479d1e1a81f0fd1e633d/src/store/actions.js#L2-L40

**Comment by OriStranac** [comment]
Fixed.
